### PR TITLE
Auth options for Heroku

### PR DESCRIPTION
**Pull request by stujo**
HI

Was trying this out and found the need to have the auth option on redis when deployed on Heroku (worked fine locally without)

So added some options and updated the README.md for your review

Cheers
Stujo

### CODE REVIEW

**Comment by mcoeur** [comment]
:+1: 

This is EXACTLY what i needed.

I came here to click the fork button when I saw your pull request, well done !

I would love to see this included in npm :-)

**Comment by stujo** [comment]
Thanks @mcoeur - I hope it works well for you

**Comment by rubenv** [comment]
Looking good! Will test & merge soon.

**Comment by rubenv** [comment]
Thanks a lot! I've just released this change:

```
published version 1.0.0 to npm
```

**Comment by stujo** [comment]
:+1:

**Pull request merged**
